### PR TITLE
Feat: Add variable ADC resolution

### PR DESCRIPTION
**Pull request by Tomcat-42**
First of all, great library!!!

I've tried to used it in an ESP32 dev board, and I noticed that the ADC resolution used for analog readings was hardcoded. For most arduinos, the ADC resolution is 10 bits (1024), but for example the ESP32 is 12 bits (4096).

So, considering this, I've added this as a constructor parameter. Also, I did some minor tweaks like refactoring magic numbers into macros for increased readability.

PS: Can you please add the flag `hacktoberfest-accepted` to this pr?

Thanks!!!!

### CODE REVIEW

**Comment by nthnn** [comment]
Hey! Just finished reviewing changes from your pull request. I wasn't aware of that thing about ADC. I might as well update a lot of things on this library. Also, I'd like to flag your pull request with `hacktoberfest-accepted` but I honestly don't know how to.

Thank you for contributing!!!

**Review by nthnn — APPROVED** [review]
Hey! Just finished reviewing changes from your pull request. I wasn't aware of that thing about ADC. I might as well update a lot of things on this library. Also, I'd like to flag your pull request with `hacktoberfest-accepted` but I honestly don't know how to; show I do it before merging or what?

Thank you for contributing!!!

**Comment by Tomcat-42** [comment]
Thanks for the feedback @nthnn !!!

It's very simple, you can follow this guide: https://www.blinkops.com/blog/creating-and-adding-labels-to-github-pull-requests-and-issues.

**Comment by Tomcat-42** [comment]
And about updating the library, I'll be happy to hear your ideas and contributing to this lib. Feel free to create issues for new features and @ me in those, for I will be glad to get involved.

**Comment by nthnn** [comment]
Well, right now I'm thinking of adding CI workflow for Arduino Library linting and might use Doxygen instead for documentations. Anyhow, I'll merge your PR now.

Thanks!

**Comment by Tomcat-42** [comment]
cheers 🎉🎉🎉

**Pull request merged**
